id: P3473252B
initial_creation_type: input
source_metadata:
  title: Tsangpa Gyare Yeshe Dorje
  language: en
  description: 'Texts by and about Tsangpa Gyare Yeshe Dorje (gtsang pa rgya ras ye
    shes rdo rje, 1161–1211), the founder of Druk Monastery:'
  volume:
    3d13ee92d90244c9a901287f46ecb5a2:
      title: The Fourfold 'Manam' Refuge
      parent: Prayers
created_at: '2022-03-01T01:54:13.256314'
last_modified_at: '2022-03-01T01:54:13.256320'
